# Configuration file for the Sphinx documentation builder.
import sys
import os
import glob
import inspect

if 'SPHINX' not in os.environ: os.environ[ 'SPHINX' ] = '1'
try: 
    import Sam54000_eeg_modules
except ImportError:
	sys.path.insert( 0, os.path.realpath( '../python' ) )
	import Sam54000_eeg_modules
	sys.modules['Sam54000_eeg_modules']


# -- Project information

project = 'Sam54000_eeg_modules'
copyright = '2023, Samuel Louviot'
author = 'Samuel Louviot'

release = '0.0.23'
version = '0.0.23'

# -- General configuration
#sys.path.insert(0,os.path.abspath('User/samuel/codes/Sam54000_eeg_modules'))
#sys.path.append(os.path.abspath('sphinxext'))

extensions = [
	'sphinx.ext.autodoc',
	#'sphinx.ext.autosummary',
	# 'sphinx.ext.doctest',
	'sphinx.ext.todo',
	'sphinx.ext.coverage',
	'sphinx.ext.mathjax',
	#'sphinx.ext.viewcode',
	'sphinx.ext.napoleon',
	'sphinx.ext.autosectionlabel',
]

intersphinx_mapping = {
    'python': ('https://docs.python.org/3/', None),
    'sphinx': ('https://www.sphinx-doc.org/en/master/', None),
    'mne': ('https://mne.tools/stable/', None),
    'mne_bids': ('https://mne.tools/mne-bids/stable/', None),
    'numpy': ('https://numpy.org/doc/stable/', None),
}
intersphinx_disabled_domains = ['std']

default_role = 'py:obj'  # role for `single-backtick-quoted strings` (put them in <pre></pre> and try to link them to autodoc)

add_module_names = False

# options for sphinx.ext.napoleon  - see http://www.sphinx-doc.org/en/stable/ext/napoleon.html#google-vs-numpy
napoleon_google_docstring = True
napoleon_numpy_docstring  = False
napoleon_use_param = False
napoleon_use_ivar = False

# options for sphinx.ext.autodoc   - see http://www.sphinx-doc.org/en/stable/ext/autodoc.html
autoclass_content = 'both'   #
autodoc_member_order = 'groupwise'

# options for sphinx.ext.autosectionlabel - see http://www.sphinx-doc.org/en/stable/ext/autosectionlabel.html
autosectionlabel_prefix_document = True

# options for sphinx.ext.autosummary - see http://www.sphinx-doc.org/en/stable/ext/autosummary.html
autosummary_generate = True


# Add any paths that contain templates here, relative to this directory.
templates_path = [ '_templates' ]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = [
	'_build', 'Thumbs.db', '.DS_Store',
	'./*.py',
]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme' # basic, classic, traditional, sphinxdoc, scrolls, alabaster, agogo, haiku... ( see http://www.sphinx-doc.org/en/stable/theming.html )
# NB: 'sphinx_rtd_theme' is nice but be aware it has to be installed via `pip install sphinx_rtd_theme`

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = [
	#'_static',
]

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# This is required for the alabaster theme
# refs: http://alabaster.readthedocs.io/en/latest/installation.html#sidebars
html_sidebars = {
	'**': [
		'relations.html',  # needs 'show_related': True theme option to display
		'searchbox.html',
	],
}
